-- Generated from:
-- docs/architecture/database/erd/erd-normalized-er-model.md
--
-- Purpose:
-- Architecture-oriented PostgreSQL DDL for ChartDB import and temporary structural
-- validation only. This file is not a canonical bootstrap or migration.
--
-- Notes:
-- 1. Cross-context logical links from the ERD are intentionally kept as plain BIGINT
--    columns without FOREIGN KEY constraints.
-- 2. The updated_at trigger logic from the ERD is intentionally omitted here to keep
--    the script ChartDB-friendly. Columns are still present with DEFAULT now().

SET search_path TO public;

CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS facility;
CREATE SCHEMA IF NOT EXISTS client;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS pii;
CREATE SCHEMA IF NOT EXISTS employee;
CREATE SCHEMA IF NOT EXISTS tariff;
CREATE SCHEMA IF NOT EXISTS contract;
CREATE SCHEMA IF NOT EXISTS booking;
CREATE SCHEMA IF NOT EXISTS "session";
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS support;
CREATE SCHEMA IF NOT EXISTS report;

CREATE TYPE client_type_enum AS ENUM ('FL', 'UL');
CREATE TYPE client_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING');
CREATE TYPE client_account_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING_VERIFICATION');
CREATE TYPE notification_channel_enum AS ENUM ('SMS', 'EMAIL', 'PUSH');
CREATE TYPE passport_document_type_enum AS ENUM ('RF_PASSPORT', 'FOREIGN_PASSPORT', 'TEMP_ID');
CREATE TYPE benefit_document_type_enum AS ENUM ('CERTIFICATE', 'ID_CARD', 'BOOKLET', 'OTHER');
CREATE TYPE benefit_document_verification_status_enum AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE organization_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING');
CREATE TYPE employee_status_enum AS ENUM ('ACTIVE', 'DISMISSED');
CREATE TYPE employee_account_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'SUSPENDED');
CREATE TYPE access_point_type_enum AS ENUM ('MANUAL', 'AUTOMATIC', 'SEMI_AUTO');
CREATE TYPE access_point_direction_enum AS ENUM ('ENTRY', 'EXIT', 'BIDIRECTIONAL');
CREATE TYPE billing_step_unit_enum AS ENUM ('MINUTE', 'HOUR', 'DAY');
CREATE TYPE contract_template_type_enum AS ENUM ('INDIVIDUAL', 'CORPORATE');
CREATE TYPE contract_signing_route_enum AS ENUM (
    'CLIENT_SMS_ACCEPTANCE',
    'EDO_CLIENT_THEN_OWNER',
    'MANUAL_SIGNED_ORIGINAL'
);
CREATE TYPE contract_signing_status_enum AS ENUM (
    'DRAFT',
    'UNDER_REVIEW',
    'AWAITING_CLIENT_SIGNATURE',
    'AWAITING_OWNER_SIGNATURE',
    'SIGNED',
    'REJECTED_BY_CLIENT',
    'REJECTED_BY_OWNER',
    'SIGNING_EXPIRED',
    'CANCELLED'
);
CREATE TYPE contract_lifecycle_status_enum AS ENUM (
    'PENDING_ACTIVATION',
    'ACTIVE',
    'SUSPENDED',
    'CANCELLED',
    'EXPIRED',
    'TERMINATED'
);
CREATE TYPE booking_type_enum AS ENUM ('AUTO', 'SHORT_TERM', 'CONTRACT');
CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE invoice_type_enum AS ENUM ('SINGLE', 'PERIODIC');
CREATE TYPE invoice_status_enum AS ENUM ('ISSUED', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE parking_session_status_enum AS ENUM ('ACTIVE', 'COMPLETED');
CREATE TYPE payment_status_enum AS ENUM ('INITIATED', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED');
CREATE TYPE receipt_fiscal_status_enum AS ENUM ('PENDING', 'ISSUED', 'FAILED');
CREATE TYPE refund_status_enum AS ENUM ('INITIATED', 'COMPLETED', 'FAILED');
CREATE TYPE debt_status_enum AS ENUM ('ACTIVE', 'PAID', 'WRITTEN_OFF');
CREATE TYPE subject_entity_enum AS ENUM ('BOOKING', 'SESSION', 'PAYMENT', 'RECEIPT', 'CONTRACT');
CREATE TYPE notification_delivery_status_enum AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED');
CREATE TYPE appeal_type_enum AS ENUM ('COMPLAINT', 'QUESTION', 'REQUEST', 'FEEDBACK');
CREATE TYPE appeal_channel_enum AS ENUM ('APP', 'EMAIL', 'PHONE', 'CHAT');
CREATE TYPE appeal_status_enum AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE access_log_direction_enum AS ENUM ('IN', 'OUT');
CREATE TYPE access_decision_enum AS ENUM ('ALLOW', 'DENY', 'MANUAL');

CREATE TABLE facility.parking_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.zone_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.vehicle_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.operational_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE shared.benefit_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE shared.outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ
);

CREATE TABLE client.agreement_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employee.employee_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariff.tariff_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE client.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type client_type_enum NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(320),
    status client_status_enum NOT NULL,
    status_reason TEXT,
    last_name VARCHAR(100),
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.parkings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address TEXT NOT NULL,
    parking_type_id BIGINT NOT NULL REFERENCES facility.parking_types(id),
    description TEXT,
    operational_status_id BIGINT NOT NULL REFERENCES facility.operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.parking_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES facility.parkings(id),
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    open_time TIME,
    close_time TIME,
    is_closed BOOLEAN NOT NULL DEFAULT false,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_facility_parking_schedules UNIQUE (parking_id, day_of_week, effective_from)
);

CREATE TABLE facility.sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES facility.parkings(id),
    zone_type_id BIGINT NOT NULL REFERENCES facility.zone_types(id),
    name VARCHAR(200) NOT NULL,
    operational_status_id BIGINT NOT NULL REFERENCES facility.operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.zone_type_vehicle_types (
    zone_type_id BIGINT NOT NULL REFERENCES facility.zone_types(id),
    vehicle_type_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (zone_type_id, vehicle_type_id)
);

CREATE TABLE facility.access_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES facility.parkings(id),
    name VARCHAR(200) NOT NULL,
    type access_point_type_enum NOT NULL,
    direction access_point_direction_enum NOT NULL,
    operational_status_id BIGINT NOT NULL REFERENCES facility.operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariff.tariffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    tariff_type_id BIGINT NOT NULL REFERENCES tariff.tariff_types(id),
    benefit_category_id BIGINT REFERENCES shared.benefit_categories(id),
    billing_step_unit billing_step_unit_enum NOT NULL,
    billing_step_value INTEGER NOT NULL DEFAULT 1,
    max_amount_minor BIGINT,
    grace_period_minutes INTEGER NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE facility.zone_type_tariffs (
    zone_type_id BIGINT NOT NULL REFERENCES facility.zone_types(id),
    tariff_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (zone_type_id, tariff_id)
);

CREATE TABLE facility.parking_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id BIGINT NOT NULL REFERENCES facility.sectors(id),
    override_tariff_id BIGINT,
    place_number VARCHAR(32) NOT NULL,
    is_occupied BOOLEAN NOT NULL DEFAULT false,
    operational_status_id BIGINT NOT NULL REFERENCES facility.operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth.client_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    auth_provider VARCHAR(64) NOT NULL,
    login VARCHAR(255),
    phone_e164 VARCHAR(32),
    email_normalized VARCHAR(320),
    password_hash VARCHAR(255),
    provider_subject_id VARCHAR(255),
    account_status client_account_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE client.notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES client.clients(id),
    parking_session_enabled BOOLEAN NOT NULL DEFAULT false,
    booking_enabled BOOLEAN NOT NULL DEFAULT false,
    contract_enabled BOOLEAN NOT NULL DEFAULT false,
    payment_enabled BOOLEAN NOT NULL DEFAULT false,
    marketing_enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE client.notification_settings_channels (
    settings_id BIGINT NOT NULL REFERENCES client.notification_settings(id),
    channel notification_channel_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (settings_id, channel)
);

CREATE TABLE client.payment_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES client.clients(id),
    external_payer_id VARCHAR(100),
    auto_debit_contract BOOLEAN NOT NULL DEFAULT false,
    auto_debit_parking_session BOOLEAN NOT NULL DEFAULT false,
    monthly_limit_minor BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pii.passport_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type passport_document_type_enum NOT NULL,
    series BYTEA NOT NULL,
    number BYTEA NOT NULL,
    issue_date DATE NOT NULL,
    issued_by BYTEA,
    department_code BYTEA,
    client_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pii.benefit_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benefit_category_id BIGINT NOT NULL,
    document_type benefit_document_type_enum NOT NULL,
    document_number VARCHAR(64) NOT NULL,
    issue_date DATE NOT NULL,
    expiry_date DATE,
    document_ref VARCHAR(512),
    verification_status benefit_document_verification_status_enum NOT NULL,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (client_id, benefit_category_id)
);

CREATE TABLE client.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES client.clients(id),
    name VARCHAR(500) NOT NULL,
    legal_form VARCHAR(64),
    legal_address TEXT,
    actual_address TEXT,
    inn VARCHAR(12) NOT NULL UNIQUE,
    kpp VARCHAR(9),
    ogrn VARCHAR(13) UNIQUE,
    email VARCHAR(320),
    phone VARCHAR(32),
    status organization_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE client.organization_bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES client.organizations(id),
    bank_name VARCHAR(255) NOT NULL,
    bik VARCHAR(9) NOT NULL,
    account_number VARCHAR(32) NOT NULL,
    correspondent_account VARCHAR(32),
    is_primary BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE client.agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client.clients(id),
    agreement_type_id BIGINT NOT NULL REFERENCES client.agreement_types(id),
    accepted BOOLEAN NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employee.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES employee.employee_roles(id),
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    phone VARCHAR(32),
    email VARCHAR(320),
    status employee_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth.employee_accounts (
    employee_id BIGINT PRIMARY KEY,
    login VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    totp_secret_encrypted TEXT,
    account_status employee_account_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE client.vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client.clients(id),
    vehicle_type_id BIGINT NOT NULL,
    license_plate VARCHAR(32) NOT NULL UNIQUE,
    brand VARCHAR(100),
    model VARCHAR(100),
    color VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariff.tariff_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id BIGINT NOT NULL REFERENCES tariff.tariffs(id),
    rate_minor BIGINT NOT NULL CHECK (rate_minor >= 0),
    day_of_week SMALLINT CHECK (day_of_week BETWEEN 1 AND 7),
    time_from TIME,
    time_to TIME,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE contract.contract_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    version VARCHAR(32) NOT NULL,
    type contract_template_type_enum NOT NULL,
    body TEXT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE contract.contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client.clients(id),
    contract_template_id BIGINT REFERENCES contract.contract_templates(id),
    contract_number VARCHAR(64) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE,
    lifecycle_status contract_lifecycle_status_enum NOT NULL DEFAULT 'PENDING_ACTIVATION',
    current_signing_attempt_id BIGINT,
    lifecycle_version BIGINT NOT NULL DEFAULT 0,
    activated_at TIMESTAMPTZ,
    terminated_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_contracts_date_range CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT chk_contracts_lifecycle_version CHECK (lifecycle_version >= 0),
    CONSTRAINT chk_contracts_terminated_at CHECK (
        (lifecycle_status = 'TERMINATED') = (terminated_at IS NOT NULL)
    ),
    CONSTRAINT chk_contracts_archived_terminal CHECK (
        archived_at IS NULL
        OR lifecycle_status IN ('CANCELLED', 'EXPIRED', 'TERMINATED')
    )
);

CREATE TABLE contract.contract_signing_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contract.contracts(id),
    attempt_no INTEGER NOT NULL,
    signing_route contract_signing_route_enum NOT NULL,
    signing_status contract_signing_status_enum NOT NULL DEFAULT 'DRAFT',
    document_version VARCHAR(64) NOT NULL,
    edo_provider_code VARCHAR(64),
    edo_document_id VARCHAR(255),
    outbound_idempotency_key VARCHAR(128),
    document_file_ref VARCHAR(512),
    client_signed_at TIMESTAMPTZ,
    owner_signed_at TIMESTAMPTZ,
    manual_verified_at TIMESTAMPTZ,
    signature_deadline_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_contract_signing_attempts_contract_attempt UNIQUE (contract_id, attempt_no),
    CONSTRAINT uq_contract_signing_attempts_id_contract UNIQUE (id, contract_id),
    CONSTRAINT chk_contract_signing_attempts_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT chk_contract_signing_attempts_version CHECK (version >= 0),
    CONSTRAINT chk_contract_signing_attempts_edo_pair CHECK (
        (edo_provider_code IS NULL) = (edo_document_id IS NULL)
    ),
    CONSTRAINT chk_contract_signing_attempts_edo_route CHECK (
        signing_route = 'EDO_CLIENT_THEN_OWNER'
        OR (edo_provider_code IS NULL AND edo_document_id IS NULL)
    ),
    CONSTRAINT chk_contract_signing_attempts_route_status CHECK (
        (
            signing_status <> 'AWAITING_OWNER_SIGNATURE'
            OR (
                signing_route = 'EDO_CLIENT_THEN_OWNER'
                AND client_signed_at IS NOT NULL
            )
        )
        AND (
            signing_status <> 'SIGNED'
            OR (
                signing_route = 'CLIENT_SMS_ACCEPTANCE'
                AND client_signed_at IS NOT NULL
            )
            OR (
                signing_route = 'EDO_CLIENT_THEN_OWNER'
                AND client_signed_at IS NOT NULL
                AND owner_signed_at IS NOT NULL
                AND document_file_ref IS NOT NULL
            )
            OR (
                signing_route = 'MANUAL_SIGNED_ORIGINAL'
                AND manual_verified_at IS NOT NULL
            )
        )
    ),
    CONSTRAINT chk_contract_signing_attempts_completed CHECK (
        (signing_status IN (
            'SIGNED',
            'REJECTED_BY_CLIENT',
            'REJECTED_BY_OWNER',
            'SIGNING_EXPIRED',
            'CANCELLED'
        )) = (completed_at IS NOT NULL)
    )
);

ALTER TABLE contract.contracts
    ADD CONSTRAINT fk_contracts_current_signing_attempt_same_contract
    FOREIGN KEY (current_signing_attempt_id, id)
    REFERENCES contract.contract_signing_attempts (id, contract_id);

-- Append-only audit history. Runtime UPDATE/DELETE privileges are configured outside
-- this ChartDB-oriented structural export.
CREATE TABLE contract.contract_signing_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signing_attempt_id BIGINT NOT NULL REFERENCES contract.contract_signing_attempts(id),
    sequence_no BIGINT NOT NULL,
    transition_id VARCHAR(64) NOT NULL,
    old_status contract_signing_status_enum,
    new_status contract_signing_status_enum NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_ref VARCHAR(128),
    source_type VARCHAR(64) NOT NULL,
    source_event_id VARCHAR(255),
    reason_code VARCHAR(64),
    reason_text TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_contract_signing_history_sequence UNIQUE (signing_attempt_id, sequence_no),
    CONSTRAINT chk_contract_signing_history_sequence CHECK (sequence_no > 0),
    CONSTRAINT chk_contract_signing_history_actor_type CHECK (
        actor_type IN ('CLIENT', 'OWNER', 'EMPLOYEE', 'SYSTEM')
    ),
    CONSTRAINT chk_contract_signing_history_status_change CHECK (
        old_status IS NULL OR old_status <> new_status
    )
);

-- Append-only audit history. L-08/L-09 are client termination transitions;
-- L-10/L-11 are parking-side termination transitions.
CREATE TABLE contract.contract_lifecycle_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contract.contracts(id),
    sequence_no BIGINT NOT NULL,
    transition_id VARCHAR(64) NOT NULL,
    old_status contract_lifecycle_status_enum,
    new_status contract_lifecycle_status_enum NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_ref VARCHAR(128),
    source_type VARCHAR(64) NOT NULL,
    source_event_id VARCHAR(255),
    reason_code VARCHAR(64),
    reason_text TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_contract_lifecycle_history_sequence UNIQUE (contract_id, sequence_no),
    CONSTRAINT chk_contract_lifecycle_history_sequence CHECK (sequence_no > 0),
    CONSTRAINT chk_contract_lifecycle_history_actor_type CHECK (
        actor_type IN ('CLIENT', 'OWNER', 'EMPLOYEE', 'SYSTEM')
    ),
    CONSTRAINT chk_contract_lifecycle_history_status_change CHECK (
        old_status IS NULL OR old_status <> new_status
    ),
    CONSTRAINT chk_contract_lifecycle_history_termination CHECK (
        (
            transition_id NOT IN ('L-08', 'L-09', 'L-10', 'L-11')
            AND new_status <> 'TERMINATED'
        )
        OR (
            transition_id = 'L-08'
            AND old_status = 'ACTIVE'
            AND new_status = 'TERMINATED'
            AND actor_type = 'CLIENT'
            AND reason_code IS NOT NULL
        )
        OR (
            transition_id = 'L-09'
            AND old_status = 'SUSPENDED'
            AND new_status = 'TERMINATED'
            AND actor_type = 'CLIENT'
            AND reason_code IS NOT NULL
        )
        OR (
            transition_id = 'L-10'
            AND old_status = 'ACTIVE'
            AND new_status = 'TERMINATED'
            AND actor_type IN ('OWNER', 'EMPLOYEE')
            AND actor_ref IS NOT NULL
            AND reason_code IS NOT NULL
        )
        OR (
            transition_id = 'L-11'
            AND old_status = 'SUSPENDED'
            AND new_status = 'TERMINATED'
            AND actor_type IN ('OWNER', 'EMPLOYEE')
            AND actor_ref IS NOT NULL
            AND reason_code IS NOT NULL
        )
    )
);

CREATE TABLE contract.contract_inbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_code VARCHAR(64) NOT NULL,
    external_event_id VARCHAR(255) NOT NULL,
    signing_attempt_id BIGINT REFERENCES contract.contract_signing_attempts(id),
    event_type VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    error_text TEXT,
    CONSTRAINT uq_contract_inbox_provider_event UNIQUE (provider_code, external_event_id)
);

CREATE VIEW contract.v_contract_current_state AS
SELECT
    c.id AS contract_id,
    c.client_id,
    c.contract_number,
    c.start_date,
    c.end_date,
    c.lifecycle_status,
    c.lifecycle_version,
    c.activated_at,
    c.terminated_at,
    c.archived_at,
    c.current_signing_attempt_id,
    a.attempt_no,
    a.signing_route,
    a.signing_status,
    a.document_version,
    a.client_signed_at,
    a.owner_signed_at,
    a.manual_verified_at,
    a.signature_deadline_at,
    a.completed_at,
    c.created_at AS contract_created_at,
    c.updated_at AS contract_updated_at,
    a.updated_at AS signing_attempt_updated_at
FROM contract.contracts AS c
LEFT JOIN contract.contract_signing_attempts AS a
    ON a.id = c.current_signing_attempt_id
    AND a.contract_id = c.id;

CREATE VIEW contract.v_access_active_contract_by_client AS
SELECT *
FROM contract.v_contract_current_state
WHERE lifecycle_status = 'ACTIVE'
  AND archived_at IS NULL
  AND signing_status = 'SIGNED';

CREATE TABLE booking.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_number VARCHAR(64) NOT NULL UNIQUE,
    vehicle_id BIGINT NOT NULL,
    parking_place_id BIGINT,
    contract_id BIGINT,
    tariff_id BIGINT NOT NULL,
    tariff_billing_step_unit billing_step_unit_enum NOT NULL,
    tariff_billing_step_value INTEGER NOT NULL,
    tariff_rate_minor BIGINT NOT NULL,
    tariff_grace_period_minutes INTEGER NOT NULL DEFAULT 0,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ,
    license_plate_snapshot VARCHAR(32) NOT NULL,
    type booking_type_enum NOT NULL,
    status booking_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE booking.booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES booking.bookings(id),
    old_status booking_status_enum,
    new_status booking_status_enum NOT NULL,
    changed_by_employee_id BIGINT,
    changed_by_client_id BIGINT,
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    contract_id BIGINT,
    invoice_number VARCHAR(64) NOT NULL UNIQUE,
    type invoice_type_enum NOT NULL,
    status invoice_status_enum NOT NULL,
    amount_due_minor BIGINT NOT NULL,
    billing_period_from DATE,
    billing_period_to DATE,
    issued_date DATE NOT NULL,
    due_date DATE,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_payment_invoices_type_shape CHECK (
        (
            type = 'PERIODIC'
            AND contract_id IS NOT NULL
            AND billing_period_from IS NOT NULL
            AND billing_period_to IS NOT NULL
            AND booking_id IS NULL
        )
        OR
        (
            type = 'SINGLE'
            AND booking_id IS NOT NULL
            AND contract_id IS NULL
            AND billing_period_from IS NULL
            AND billing_period_to IS NULL
        )
    )
);

CREATE TABLE "session".parking_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    exit_time TIMESTAMPTZ,
    status parking_session_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES payment.invoices(id),
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'RUB',
    payment_method_id BIGINT NOT NULL REFERENCES payment.payment_methods(id),
    status payment_status_enum NOT NULL,
    initiated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    provider_id VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment.payments(id),
    fiscal_number VARCHAR(64) NOT NULL UNIQUE,
    receipt_at TIMESTAMPTZ NOT NULL,
    fiscal_status receipt_fiscal_status_enum NOT NULL,
    amount_minor BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment.payments(id),
    amount_minor BIGINT NOT NULL,
    reason TEXT,
    refund_provider_id VARCHAR(512),
    status refund_status_enum NOT NULL,
    initiated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment.debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES payment.invoices(id),
    client_id BIGINT NOT NULL,
    amount_minor BIGINT NOT NULL,
    remaining_amount_minor BIGINT NOT NULL CHECK (
        remaining_amount_minor >= 0
        AND remaining_amount_minor <= amount_minor
    ),
    overdue_since DATE NOT NULL,
    status debt_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification.notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    channel notification_channel_enum NOT NULL,
    subject VARCHAR(500),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_template_id BIGINT REFERENCES notification.notification_templates(id),
    client_id BIGINT NOT NULL,
    initiator_employee_id BIGINT,
    subject_type subject_entity_enum,
    subject_id BIGINT,
    channel notification_channel_enum NOT NULL,
    delivery_address VARCHAR(320) NOT NULL,
    delivery_status notification_delivery_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_notification_notifications_subject_pair CHECK (
        (subject_type IS NULL) = (subject_id IS NULL)
    )
);

CREATE TABLE support.appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    employee_id BIGINT,
    subject_type subject_entity_enum,
    subject_id BIGINT,
    type appeal_type_enum NOT NULL,
    channel appeal_channel_enum NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    status appeal_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_support_appeals_subject_pair CHECK (
        (subject_type IS NULL) = (subject_id IS NULL)
    )
);

CREATE TABLE report.access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_point_id BIGINT NOT NULL,
    parking_session_id BIGINT,
    vehicle_id BIGINT,
    direction access_log_direction_enum NOT NULL,
    decision access_decision_enum NOT NULL,
    reason TEXT,
    decided_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Performance indexes from the ERD.
-- Core ChartDB import usually relies on CREATE TYPE / CREATE TABLE / constraints.
-- If a specific ChartDB import run does not accept advanced PostgreSQL indexes,
-- keep the schema block above and remove only this index section.

CREATE UNIQUE INDEX uq_client_organization_bank_accounts_primary
    ON client.organization_bank_accounts (organization_id)
    WHERE is_primary = true;

CREATE UNIQUE INDEX uq_auth_client_accounts_phone_e164
    ON auth.client_accounts (phone_e164)
    WHERE phone_e164 IS NOT NULL;

CREATE UNIQUE INDEX uq_auth_client_accounts_email_normalized
    ON auth.client_accounts (email_normalized)
    WHERE email_normalized IS NOT NULL;

CREATE UNIQUE INDEX uq_auth_client_accounts_provider_subject
    ON auth.client_accounts (auth_provider, provider_subject_id)
    WHERE provider_subject_id IS NOT NULL;

CREATE UNIQUE INDEX uq_payment_payments_provider_id
    ON payment.payments (provider_id)
    WHERE provider_id IS NOT NULL;

CREATE UNIQUE INDEX uq_payment_refunds_refund_provider_id
    ON payment.refunds (refund_provider_id)
    WHERE refund_provider_id IS NOT NULL;

CREATE UNIQUE INDEX uq_tariff_tariff_rates_applicability
    ON tariff.tariff_rates (
        tariff_id,
        COALESCE(day_of_week, 0),
        COALESCE(time_from, '00:00'::TIME),
        COALESCE(time_to, '00:00'::TIME)
    );

CREATE INDEX idx_booking_bookings_status_active_pending
    ON booking.bookings (status)
    WHERE status IN ('ACTIVE', 'PENDING');

CREATE INDEX idx_booking_bookings_start_at_end_at
    ON booking.bookings (start_at, end_at);

CREATE INDEX idx_booking_bookings_vehicle_id
    ON booking.bookings (vehicle_id);

CREATE INDEX idx_booking_bookings_parking_place_id
    ON booking.bookings (parking_place_id);

CREATE INDEX idx_booking_bookings_contract_id
    ON booking.bookings (contract_id);

CREATE INDEX idx_booking_bookings_tariff_id
    ON booking.bookings (tariff_id);

CREATE INDEX idx_session_parking_sessions_status_active
    ON "session".parking_sessions (status)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_session_parking_sessions_entry_time_desc
    ON "session".parking_sessions (entry_time DESC);

CREATE INDEX idx_session_parking_sessions_booking_id
    ON "session".parking_sessions (booking_id);

CREATE INDEX idx_payment_invoices_status
    ON payment.invoices (status);

CREATE INDEX idx_payment_invoices_booking_id
    ON payment.invoices (booking_id);

CREATE INDEX idx_payment_invoices_contract_id
    ON payment.invoices (contract_id);

CREATE INDEX idx_payment_invoices_due_date_open
    ON payment.invoices (due_date)
    WHERE status NOT IN ('PAID', 'CANCELLED');

CREATE INDEX idx_payment_payments_invoice_id
    ON payment.payments (invoice_id);

CREATE INDEX idx_payment_payments_invoice_id_status_amount_completed
    ON payment.payments (invoice_id, status, amount_minor)
    WHERE status = 'COMPLETED';

CREATE INDEX idx_payment_payments_status_open
    ON payment.payments (status)
    WHERE status NOT IN ('COMPLETED', 'CANCELLED');

CREATE INDEX idx_payment_payments_payment_method_id
    ON payment.payments (payment_method_id);

CREATE INDEX idx_payment_receipts_payment_id
    ON payment.receipts (payment_id);

CREATE INDEX idx_payment_refunds_payment_id
    ON payment.refunds (payment_id);

CREATE INDEX idx_payment_debts_invoice_id
    ON payment.debts (invoice_id);

CREATE INDEX idx_payment_debts_client_id
    ON payment.debts (client_id);

CREATE INDEX idx_payment_debts_status_active
    ON payment.debts (status)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_contract_contracts_client_id
    ON contract.contracts (client_id);

CREATE INDEX idx_contract_contracts_contract_template_id
    ON contract.contracts (contract_template_id);

CREATE INDEX idx_contract_contracts_current_signing_attempt_id
    ON contract.contracts (current_signing_attempt_id);

CREATE INDEX idx_contract_contracts_client_lifecycle
    ON contract.contracts (client_id, lifecycle_status);

CREATE INDEX idx_contract_contracts_active_by_client
    ON contract.contracts (client_id)
    WHERE lifecycle_status = 'ACTIVE' AND archived_at IS NULL;

CREATE INDEX idx_contract_signing_attempts_contract_id
    ON contract.contract_signing_attempts (contract_id);

CREATE UNIQUE INDEX uq_contract_signing_attempts_edo_document
    ON contract.contract_signing_attempts (edo_provider_code, edo_document_id)
    WHERE edo_provider_code IS NOT NULL AND edo_document_id IS NOT NULL;

CREATE UNIQUE INDEX uq_contract_signing_attempts_outbound_idempotency
    ON contract.contract_signing_attempts (outbound_idempotency_key)
    WHERE outbound_idempotency_key IS NOT NULL;

CREATE INDEX idx_contract_signing_history_attempt_occurred
    ON contract.contract_signing_status_history (signing_attempt_id, occurred_at DESC);

CREATE UNIQUE INDEX uq_contract_signing_history_source_event
    ON contract.contract_signing_status_history (source_type, source_event_id)
    WHERE source_event_id IS NOT NULL;

CREATE INDEX idx_contract_lifecycle_history_contract_occurred
    ON contract.contract_lifecycle_status_history (contract_id, occurred_at DESC);

CREATE UNIQUE INDEX uq_contract_lifecycle_history_source_event
    ON contract.contract_lifecycle_status_history (source_type, source_event_id)
    WHERE source_event_id IS NOT NULL;

CREATE INDEX idx_contract_inbox_signing_attempt_id
    ON contract.contract_inbox_events (signing_attempt_id);

CREATE INDEX idx_contract_inbox_unprocessed
    ON contract.contract_inbox_events (received_at)
    WHERE processed_at IS NULL;

CREATE INDEX idx_client_vehicles_client_id
    ON client.vehicles (client_id);

CREATE INDEX idx_client_agreements_client_id
    ON client.agreements (client_id);

CREATE INDEX idx_client_agreements_agreement_type_id
    ON client.agreements (agreement_type_id);

CREATE INDEX idx_notification_notifications_client_id
    ON notification.notifications (client_id);

CREATE INDEX idx_notification_notifications_template_id
    ON notification.notifications (notification_template_id);

CREATE INDEX idx_notification_notifications_subject
    ON notification.notifications (subject_type, subject_id);

CREATE INDEX idx_support_appeals_client_id
    ON support.appeals (client_id);

CREATE INDEX idx_support_appeals_employee_id
    ON support.appeals (employee_id);

CREATE INDEX idx_support_appeals_subject
    ON support.appeals (subject_type, subject_id);

CREATE INDEX idx_tariff_tariffs_tariff_type_id
    ON tariff.tariffs (tariff_type_id);

CREATE INDEX idx_tariff_tariff_rates_tariff_id
    ON tariff.tariff_rates (tariff_id);

CREATE INDEX idx_employee_employees_role_id
    ON employee.employees (role_id);

CREATE INDEX idx_facility_parkings_parking_type_id
    ON facility.parkings (parking_type_id);

CREATE INDEX idx_facility_parkings_operational_status_id
    ON facility.parkings (operational_status_id);

CREATE INDEX idx_facility_parking_schedules_parking_id
    ON facility.parking_schedules (parking_id);

CREATE INDEX idx_facility_sectors_parking_id
    ON facility.sectors (parking_id);

CREATE INDEX idx_facility_sectors_zone_type_id
    ON facility.sectors (zone_type_id);

CREATE INDEX idx_facility_sectors_operational_status_id
    ON facility.sectors (operational_status_id);

CREATE INDEX idx_facility_access_points_parking_id
    ON facility.access_points (parking_id);

CREATE INDEX idx_facility_access_points_operational_status_id
    ON facility.access_points (operational_status_id);

CREATE INDEX idx_facility_parking_places_sector_id
    ON facility.parking_places (sector_id);

CREATE INDEX idx_facility_parking_places_operational_status_id
    ON facility.parking_places (operational_status_id);

CREATE INDEX idx_client_organization_bank_accounts_organization_id
    ON client.organization_bank_accounts (organization_id);

CREATE INDEX idx_auth_client_accounts_client_id
    ON auth.client_accounts (client_id);

CREATE INDEX idx_report_access_logs_access_point_id
    ON report.access_logs (access_point_id);

CREATE INDEX idx_report_access_logs_parking_session_id_not_null
    ON report.access_logs (parking_session_id)
    WHERE parking_session_id IS NOT NULL;

CREATE INDEX idx_report_access_logs_decided_at_desc
    ON report.access_logs (decided_at DESC);

CREATE INDEX idx_report_access_logs_vehicle_id_not_null
    ON report.access_logs (vehicle_id)
    WHERE vehicle_id IS NOT NULL;
