-- Generated from:
-- docs/architecture/database/erd/erd-normalized-er-model.md
--
-- Purpose:
-- Flat PostgreSQL DDL for ChartDB import and visual ERD rendering.
--
-- Differences from the architecture-oriented script:
-- 1. All tables are placed in the default schema for simpler visualization.
-- 2. Cross-context logical links are materialized as FOREIGN KEY constraints so ChartDB
--    can render the relationships directly.
-- 3. Advanced PostgreSQL-specific indexes and nuanced runtime-only constraints are omitted
--    to keep the import simpler and the diagram cleaner.

CREATE TYPE client_type_enum AS ENUM ('FL', 'UL');
CREATE TYPE client_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING');
CREATE TYPE client_account_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING_VERIFICATION');
CREATE TYPE notification_channel_enum AS ENUM ('SMS', 'EMAIL', 'PUSH');
CREATE TYPE passport_document_type_enum AS ENUM ('RF_PASSPORT', 'FOREIGN_PASSPORT', 'TEMP_ID');
CREATE TYPE benefit_document_type_enum AS ENUM ('CERTIFICATE', 'ID_CARD', 'BOOKLET', 'OTHER');
CREATE TYPE benefit_document_verification_status_enum AS ENUM ('PENDING', 'VERIFIED', 'REJECTED');
CREATE TYPE organization_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'PENDING');
CREATE TYPE employee_status_enum AS ENUM ('ACTIVE', 'DISMISSED');
CREATE TYPE employee_account_status_enum AS ENUM ('ACTIVE', 'BLOCKED', 'SUSPENDED');
CREATE TYPE access_point_type_enum AS ENUM ('MANUAL', 'AUTOMATIC', 'SEMI_AUTO');
CREATE TYPE access_point_direction_enum AS ENUM ('ENTRY', 'EXIT', 'BIDIRECTIONAL');
CREATE TYPE billing_step_unit_enum AS ENUM ('MINUTE', 'HOUR', 'DAY');
CREATE TYPE contract_template_type_enum AS ENUM ('INDIVIDUAL', 'CORPORATE');
CREATE TYPE contract_status_enum AS ENUM ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED');
CREATE TYPE booking_type_enum AS ENUM ('AUTO', 'SHORT_TERM', 'CONTRACT');
CREATE TYPE booking_status_enum AS ENUM ('PENDING', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE invoice_type_enum AS ENUM ('SINGLE', 'PERIODIC');
CREATE TYPE invoice_status_enum AS ENUM ('ISSUED', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE parking_session_status_enum AS ENUM ('ACTIVE', 'COMPLETED');
CREATE TYPE payment_status_enum AS ENUM ('INITIATED', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED');
CREATE TYPE receipt_fiscal_status_enum AS ENUM ('PENDING', 'ISSUED', 'FAILED');
CREATE TYPE refund_status_enum AS ENUM ('INITIATED', 'COMPLETED', 'FAILED');
CREATE TYPE debt_status_enum AS ENUM ('ACTIVE', 'PAID', 'WRITTEN_OFF');
CREATE TYPE subject_entity_enum AS ENUM ('BOOKING', 'SESSION', 'PAYMENT', 'RECEIPT', 'CONTRACT');
CREATE TYPE notification_delivery_status_enum AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED');
CREATE TYPE appeal_type_enum AS ENUM ('COMPLAINT', 'QUESTION', 'REQUEST', 'FEEDBACK');
CREATE TYPE appeal_channel_enum AS ENUM ('APP', 'EMAIL', 'PHONE', 'CHAT');
CREATE TYPE appeal_status_enum AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
CREATE TYPE access_log_direction_enum AS ENUM ('IN', 'OUT');
CREATE TYPE access_decision_enum AS ENUM ('ALLOW', 'DENY', 'MANUAL');

CREATE TABLE parking_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE zone_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vehicle_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE operational_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE benefit_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agreement_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employee_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariff_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type client_type_enum NOT NULL,
    phone VARCHAR(32) NOT NULL,
    email VARCHAR(320),
    status client_status_enum NOT NULL,
    status_reason TEXT,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE parkings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address TEXT NOT NULL,
    parking_type_id BIGINT NOT NULL REFERENCES parking_types(id),
    description TEXT,
    operational_status_id BIGINT NOT NULL REFERENCES operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE parking_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES parkings(id),
    day_of_week SMALLINT NOT NULL,
    open_time TIME,
    close_time TIME,
    is_closed BOOLEAN NOT NULL DEFAULT false,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (parking_id, day_of_week, effective_from)
);

CREATE TABLE sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES parkings(id),
    zone_type_id BIGINT NOT NULL REFERENCES zone_types(id),
    name VARCHAR(200) NOT NULL,
    operational_status_id BIGINT NOT NULL REFERENCES operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE access_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_id BIGINT NOT NULL REFERENCES parkings(id),
    name VARCHAR(200) NOT NULL,
    type access_point_type_enum NOT NULL,
    direction access_point_direction_enum NOT NULL,
    operational_status_id BIGINT NOT NULL REFERENCES operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    tariff_type_id BIGINT NOT NULL REFERENCES tariff_types(id),
    benefit_category_id BIGINT REFERENCES benefit_categories(id),
    billing_step_unit billing_step_unit_enum NOT NULL,
    billing_step_value INTEGER NOT NULL DEFAULT 1,
    max_amount_minor BIGINT,
    grace_period_minutes INTEGER NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE zone_type_vehicle_types (
    zone_type_id BIGINT NOT NULL REFERENCES zone_types(id),
    vehicle_type_id BIGINT NOT NULL REFERENCES vehicle_types(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (zone_type_id, vehicle_type_id)
);

CREATE TABLE zone_type_tariffs (
    zone_type_id BIGINT NOT NULL REFERENCES zone_types(id),
    tariff_id BIGINT NOT NULL REFERENCES tariffs(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (zone_type_id, tariff_id)
);

CREATE TABLE parking_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sector_id BIGINT NOT NULL REFERENCES sectors(id),
    override_tariff_id BIGINT REFERENCES tariffs(id),
    place_number VARCHAR(12) NOT NULL,
    is_occupied BOOLEAN NOT NULL DEFAULT false,
    operational_status_id BIGINT NOT NULL REFERENCES operational_statuses(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE client_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    auth_provider VARCHAR(64) NOT NULL,
    login VARCHAR(255),
    phone VARCHAR(32) UNIQUE,
    email VARCHAR(320) UNIQUE,
    password_hash VARCHAR(255),
    provider_subject_id VARCHAR(255),
    account_status client_account_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    UNIQUE (auth_provider, provider_subject_id)
);

CREATE TABLE notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    parking_session_enabled BOOLEAN NOT NULL DEFAULT false,
    booking_enabled BOOLEAN NOT NULL DEFAULT false,
    contract_enabled BOOLEAN NOT NULL DEFAULT false,
    payment_enabled BOOLEAN NOT NULL DEFAULT false,
    marketing_enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification_settings_channels (
    settings_id BIGINT NOT NULL REFERENCES notification_settings(id),
    channel notification_channel_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (settings_id, channel)
);

CREATE TABLE payment_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    external_payer_id VARCHAR(100),
    auto_debit_contract BOOLEAN NOT NULL DEFAULT false,
    auto_debit_parking_session BOOLEAN NOT NULL DEFAULT false,
    monthly_limit_minor BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE passport_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type passport_document_type_enum NOT NULL,
    series BYTEA NOT NULL,
    number BYTEA NOT NULL,
    issue_date DATE NOT NULL,
    issued_by BYTEA,
    department_code BYTEA,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE benefit_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benefit_category_id BIGINT NOT NULL REFERENCES benefit_categories(id),
    document_type benefit_document_type_enum NOT NULL,
    document_number VARCHAR(64) NOT NULL,
    issue_date DATE NOT NULL,
    expiry_date DATE,
    document_ref VARCHAR(512),
    verification_status benefit_document_verification_status_enum NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (client_id, benefit_category_id)
);

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    name VARCHAR(500) NOT NULL,
    legal_form VARCHAR(64),
    legal_address TEXT,
    actual_address TEXT,
    inn VARCHAR(12) NOT NULL UNIQUE,
    kpp VARCHAR(9),
    ogrn VARCHAR(13) UNIQUE,
    email VARCHAR(320),
    phone VARCHAR(32),
    status organization_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE organization_bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    bank_name VARCHAR(255) NOT NULL,
    bik VARCHAR(9) NOT NULL,
    account_number VARCHAR(32) NOT NULL,
    correspondent_account VARCHAR(32),
    is_primary BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    agreement_type_id BIGINT NOT NULL REFERENCES agreement_types(id),
    accepted BOOLEAN NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES employee_roles(id),
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    phone VARCHAR(32),
    email VARCHAR(320),
    status employee_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employee_accounts (
    employee_id BIGINT PRIMARY KEY REFERENCES employees(id),
    login VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    totp_secret_encrypted TEXT,
    account_status employee_account_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    vehicle_type_id BIGINT NOT NULL REFERENCES vehicle_types(id),
    license_plate VARCHAR(32) NOT NULL UNIQUE,
    brand VARCHAR(100),
    model VARCHAR(100),
    color VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tariff_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id BIGINT NOT NULL REFERENCES tariffs(id),
    rate_minor BIGINT NOT NULL,
    day_of_week SMALLINT,
    time_from TIME,
    time_to TIME,
    priority INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tariff_id, day_of_week, time_from)
);

CREATE TABLE contract_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    version VARCHAR(32) NOT NULL,
    type contract_template_type_enum NOT NULL,
    body TEXT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    contract_template_id BIGINT REFERENCES contract_templates(id),
    contract_number VARCHAR(64) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE,
    status contract_status_enum NOT NULL,
    document_file_ref VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE contract_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(id),
    old_status contract_status_enum,
    new_status contract_status_enum NOT NULL,
    changed_by_employee_id BIGINT REFERENCES employees(id),
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_number VARCHAR(64) NOT NULL UNIQUE,
    vehicle_id BIGINT NOT NULL REFERENCES vehicles(id),
    parking_place_id BIGINT REFERENCES parking_places(id),
    contract_id BIGINT REFERENCES contracts(id),
    tariff_id BIGINT NOT NULL REFERENCES tariffs(id),
    tariff_billing_step_unit billing_step_unit_enum NOT NULL,
    tariff_billing_step_value INTEGER NOT NULL,
    tariff_rate_minor BIGINT NOT NULL,
    tariff_grace_period_minutes INTEGER NOT NULL DEFAULT 0,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ,
    license_plate_snapshot VARCHAR(32) NOT NULL,
    type booking_type_enum NOT NULL,
    status booking_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE booking_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    old_status booking_status_enum,
    new_status booking_status_enum NOT NULL,
    changed_by_employee_id BIGINT REFERENCES employees(id),
    changed_by_client_id BIGINT REFERENCES clients(id),
    reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id),
    contract_id BIGINT REFERENCES contracts(id),
    invoice_number VARCHAR(64) NOT NULL UNIQUE,
    type invoice_type_enum NOT NULL,
    status invoice_status_enum NOT NULL,
    amount_due_minor BIGINT NOT NULL,
    billing_period_from DATE,
    billing_period_to DATE,
    issued_date DATE NOT NULL,
    due_date DATE,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_invoices_has_target CHECK (booking_id IS NOT NULL OR contract_id IS NOT NULL)
);

CREATE TABLE parking_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id),
    entry_time TIMESTAMPTZ NOT NULL,
    exit_time TIMESTAMPTZ,
    status parking_session_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    amount_minor BIGINT NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'RUB',
    payment_method_id BIGINT NOT NULL REFERENCES payment_methods(id),
    status payment_status_enum NOT NULL,
    initiated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    provider_id VARCHAR(512) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id),
    fiscal_number VARCHAR(64) NOT NULL UNIQUE,
    receipt_at TIMESTAMPTZ NOT NULL,
    fiscal_status receipt_fiscal_status_enum NOT NULL,
    amount_minor BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL UNIQUE REFERENCES payments(id),
    amount_minor BIGINT NOT NULL,
    reason TEXT,
    refund_provider_id VARCHAR(512) UNIQUE,
    status refund_status_enum NOT NULL,
    initiated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    client_id BIGINT NOT NULL REFERENCES clients(id),
    amount_minor BIGINT NOT NULL,
    remaining_amount_minor BIGINT NOT NULL,
    overdue_since DATE NOT NULL,
    status debt_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    channel notification_channel_enum NOT NULL,
    subject VARCHAR(500),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_template_id BIGINT REFERENCES notification_templates(id),
    client_id BIGINT NOT NULL REFERENCES clients(id),
    initiator_employee_id BIGINT REFERENCES employees(id),
    subject_type subject_entity_enum,
    subject_id BIGINT,
    channel notification_channel_enum NOT NULL,
    delivery_address VARCHAR(320) NOT NULL,
    delivery_status notification_delivery_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_notifications_subject_pair CHECK (
        (subject_type IS NULL) = (subject_id IS NULL)
    )
);

CREATE TABLE appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    employee_id BIGINT REFERENCES employees(id),
    subject_type subject_entity_enum,
    subject_id BIGINT,
    type appeal_type_enum NOT NULL,
    channel appeal_channel_enum NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    status appeal_status_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_appeals_subject_pair CHECK (
        (subject_type IS NULL) = (subject_id IS NULL)
    )
);

-- access_logs: таблица только на добавление (append-only), без updated_at.
-- Для партиционирования по месяцам объявлять как:
--   CREATE TABLE access_logs (...) PARTITION BY RANGE (decided_at);
--   CREATE TABLE access_logs_2026_04 PARTITION OF access_logs
--       FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
-- В плоском файле для ChartDB оставлена как обычная таблица — парсер не поддерживает PARTITION BY.
CREATE TABLE access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_point_id BIGINT NOT NULL REFERENCES access_points(id),
    parking_session_id BIGINT REFERENCES parking_sessions(id),
    vehicle_id BIGINT REFERENCES vehicles(id),
    direction access_log_direction_enum NOT NULL,
    decision access_decision_enum NOT NULL,
    reason TEXT,
    decided_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ
);

-- =============================================================================
-- Operational constraints
-- Requires: CREATE EXTENSION btree_gist;
-- Вынесены отдельно, чтобы не мешать парсеру ChartDB при импорте ERD.
-- Выполнять вручную на живом PostgreSQL.
-- =============================================================================

-- Запрет двойного бронирования одного места в пересекающихся временных диапазонах.
-- CREATE EXTENSION IF NOT EXISTS btree_gist;
-- ALTER TABLE bookings
--     ADD CONSTRAINT excl_no_overlapping_bookings
--     EXCLUDE USING GIST (
--         parking_place_id WITH =,
--         tstzrange(start_at, COALESCE(end_at, 'infinity'::timestamptz), '[)') WITH &&
--     ) WHERE (
--         parking_place_id IS NOT NULL
--         AND status NOT IN ('CANCELLED', 'NO_SHOW', 'COMPLETED')
--     );
